name: Atualizar Métricas do Perfil

on:
  schedule:
    - cron: "0 * * * *" # Atualiza a cada hora
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ESSA LINHA DÁ A PERMISSÃO DE ESCRITA
    steps:
      - name: Gerador de Métricas de Engenharia
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_theme: dracula
          config_timezone: America/Sao_Paulo
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: percentage
